"""empty message

Revision ID: 014bb36af5ba
Revises: 1a78b297aa31
Create Date: 2022-05-23 12:37:24.682721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014bb36af5ba'
down_revision = '1a78b297aa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('count_seen', sa.BigInteger(), nullable=True),
    sa.Column('photo_banner', sa.Text(), nullable=True),
    sa.Column('photo_banner_url', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
