"""empty message

Revision ID: 029c236e0b61
Revises: 014bb36af5ba
Create Date: 2022-05-23 12:38:12.078189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029c236e0b61'
down_revision = '014bb36af5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
