"""empty message

Revision ID: 0708d8870fc6
Revises: 4b2a498e0e63
Create Date: 2022-05-30 13:08:08.114881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0708d8870fc6'
down_revision = '4b2a498e0e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callbackxendit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=256), nullable=True),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('ammount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callbackxendit_id'), 'callbackxendit', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_callbackxendit_id'), table_name='callbackxendit')
    op.drop_table('callbackxendit')
    # ### end Alembic commands ###
