"""empty message

Revision ID: 071c6483c0a1
Revises: c7f7d6bb5eea
Create Date: 2022-05-30 17:09:24.880091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071c6483c0a1'
down_revision = 'c7f7d6bb5eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('is_stock', sa.Boolean(), nullable=True))
    op.add_column('menu', sa.Column('current_stock', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'current_stock')
    op.drop_column('menu', 'is_stock')
    # ### end Alembic commands ###
