"""empty message

Revision ID: 11d22aa2d8df
Revises: d88f159db8b8
Create Date: 2022-05-16 10:27:34.205487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d22aa2d8df'
down_revision = 'd88f159db8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('menu', sa.Column('desc', sa.String(length=384), nullable=True))
    op.add_column('menu', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('menu', sa.Column('createdAt', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'createdAt')
    op.drop_column('menu', 'is_deleted')
    op.drop_column('menu', 'desc')
    op.drop_column('menu', 'name')
    # ### end Alembic commands ###
