"""empty message

Revision ID: 11da3c9ca98c
Revises: 5a8d1c7945f8
Create Date: 2022-05-16 05:59:28.511212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11da3c9ca98c'
down_revision = '5a8d1c7945f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toko', sa.Column('createdAt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toko', 'createdAt')
    # ### end Alembic commands ###
