"""empty message

Revision ID: 1316c40a99ef
Revises: 618a7eaf9ac8
Create Date: 2022-05-16 10:56:49.791635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1316c40a99ef'
down_revision = '618a7eaf9ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('harga_asli', sa.BigInteger(), nullable=True))
    op.add_column('menu', sa.Column('harga_jual', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'harga_jual')
    op.drop_column('menu', 'harga_asli')
    # ### end Alembic commands ###
