"""empty message

Revision ID: 1914bd03be84
Revises: 4a90462a9776
Create Date: 2022-05-15 12:09:36.018067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1914bd03be84'
down_revision = '4a90462a9776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('no_rekening', sa.String(length=256), nullable=True))
    op.add_column('account', sa.Column('jenis_bank', sa.String(length=256), nullable=True))
    op.add_column('account', sa.Column('photo_profile', sa.Text(), nullable=True))
    op.add_column('account', sa.Column('photo_profile_url', sa.Text(), nullable=True))
    op.add_column('account', sa.Column('photo_norek', sa.Text(), nullable=True))
    op.add_column('account', sa.Column('photo_norek_url', sa.Text(), nullable=True))
    op.add_column('account', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_deleted')
    op.drop_column('account', 'photo_norek_url')
    op.drop_column('account', 'photo_norek')
    op.drop_column('account', 'photo_profile_url')
    op.drop_column('account', 'photo_profile')
    op.drop_column('account', 'jenis_bank')
    op.drop_column('account', 'no_rekening')
    # ### end Alembic commands ###
