"""empty message

Revision ID: 1a78b297aa31
Revises: 7f5042eb35a2
Create Date: 2022-05-23 10:12:15.555307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a78b297aa31'
down_revision = '7f5042eb35a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('photo_banner', sa.Text(), nullable=True))
    op.add_column('banner', sa.Column('photo_banner_url', sa.Text(), nullable=True))
    op.drop_column('banner', 'photo_menu_url')
    op.drop_column('banner', 'photo_menu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('photo_menu', mysql.TEXT(), nullable=True))
    op.add_column('banner', sa.Column('photo_menu_url', mysql.TEXT(), nullable=True))
    op.drop_column('banner', 'photo_banner_url')
    op.drop_column('banner', 'photo_banner')
    # ### end Alembic commands ###
