"""empty message

Revision ID: 1cc02a5a27b8
Revises: 93192f2ba992
Create Date: 2022-05-25 15:12:06.969742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc02a5a27b8'
down_revision = '93192f2ba992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('sub_total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'sub_total_price')
    # ### end Alembic commands ###
