"""empty message

Revision ID: 24e6c71e70a7
Revises: 979c6f618e00
Create Date: 2022-05-23 08:55:50.484571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e6c71e70a7'
down_revision = '979c6f618e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
