"""empty message

Revision ID: 2c1c1b63bd8d
Revises: cabb8e9bca18
Create Date: 2022-05-16 20:00:45.698412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c1c1b63bd8d'
down_revision = 'cabb8e9bca18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_toko_menu_id', table_name='toko_menu')
    op.drop_table('toko_menu')
    op.add_column('menu', sa.Column('toko_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menu', 'toko', ['toko_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_column('menu', 'toko_id')
    op.create_table('toko_menu',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('menu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('toko_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], name='toko_menu_ibfk_1'),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.id'], name='toko_menu_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_toko_menu_id', 'toko_menu', ['id'], unique=False)
    # ### end Alembic commands ###
