"""empty message

Revision ID: 2eef46a2ffd9
Revises: 49a49aaf7d05
Create Date: 2022-05-14 22:52:54.358131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eef46a2ffd9'
down_revision = '49a49aaf7d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('pwd', sa.String(length=640), nullable=True),
    sa.Column('ecd', sa.String(length=640), nullable=True),
    sa.Column('key_ecd', sa.String(length=640), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('account_type', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_table('toko',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toko_id'), 'toko', ['id'], unique=False)
    op.create_table('account_toko',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('toko_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_toko_id'), 'account_toko', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_toko_id'), table_name='account_toko')
    op.drop_table('account_toko')
    op.drop_index(op.f('ix_toko_id'), table_name='toko')
    op.drop_table('toko')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
