"""empty message

Revision ID: 340763221357
Revises: b0fab7af7728
Create Date: 2022-05-14 12:25:59.667751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340763221357'
down_revision = 'b0fab7af7728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
