"""empty message

Revision ID: 3fd7f705e42d
Revises: 1cc02a5a27b8
Create Date: 2022-05-30 10:21:55.848688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd7f705e42d'
down_revision = '1cc02a5a27b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reff_code', sa.String(length=256), nullable=True),
    sa.Column('sub_total_price', sa.Float(), nullable=True),
    sa.Column('total_pajak', sa.Float(), nullable=True),
    sa.Column('grand_total_price', sa.Float(), nullable=True),
    sa.Column('uang_bayar', sa.Float(), nullable=True),
    sa.Column('uang_kembalian', sa.Float(), nullable=True),
    sa.Column('is_cancel', sa.Boolean(), nullable=True),
    sa.Column('is_settlement', sa.Boolean(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('toko_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
