"""empty message

Revision ID: 414662f26ba2
Revises: 560aebfa9a02
Create Date: 2022-05-23 08:15:38.035572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '414662f26ba2'
down_revision = '560aebfa9a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pajak', sa.Column('type_pajak', sa.Integer(), nullable=True))
    op.drop_column('pajak', 'type_disc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pajak', sa.Column('type_disc', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('pajak', 'type_pajak')
    # ### end Alembic commands ###
