"""empty message

Revision ID: 4636abb17993
Revises: f4ae71cf20be
Create Date: 2022-05-14 12:48:43.684566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4636abb17993'
down_revision = 'f4ae71cf20be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('ecd', sa.String(length=640), nullable=True))
    op.add_column('account', sa.Column('key_ecd', sa.String(length=640), nullable=True))
    op.drop_column('account', 'key_dcd')
    op.drop_column('account', 'dcd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('dcd', mysql.VARCHAR(length=640), nullable=True))
    op.add_column('account', sa.Column('key_dcd', mysql.VARCHAR(length=640), nullable=True))
    op.drop_column('account', 'key_ecd')
    op.drop_column('account', 'ecd')
    # ### end Alembic commands ###
