"""empty message

Revision ID: 49a49aaf7d05
Revises: 7df3017ea9a6
Create Date: 2022-05-14 22:51:33.005694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a49aaf7d05'
down_revision = '7df3017ea9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_toko', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_account_toko_id'), 'account_toko', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_toko_id'), table_name='account_toko')
    op.drop_column('account_toko', 'id')
    # ### end Alembic commands ###
