"""empty message

Revision ID: 4a90462a9776
Revises: e2f1a909f28e
Create Date: 2022-05-15 00:35:40.487880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a90462a9776'
down_revision = 'e2f1a909f28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('OTP', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'OTP')
    # ### end Alembic commands ###
