"""empty message

Revision ID: 4b2a498e0e63
Revises: 676d0889b65b
Create Date: 2022-05-30 13:07:49.749103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b2a498e0e63'
down_revision = '676d0889b65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_callbackxendit_id', table_name='callbackxendit')
    op.drop_table('callbackxendit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callbackxendit',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('event', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('external_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('ammount', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_callbackxendit_id', 'callbackxendit', ['id'], unique=False)
    # ### end Alembic commands ###
