"""empty message

Revision ID: 4ea21bbc0918
Revises: fe160b0d6353
Create Date: 2022-05-20 10:22:00.059167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea21bbc0918'
down_revision = 'fe160b0d6353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pelanggan', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('pelanggan', sa.Column('phone', sa.String(length=256), nullable=True))
    op.add_column('pelanggan', sa.Column('email', sa.String(length=256), nullable=True))
    op.add_column('pelanggan', sa.Column('createdAt', sa.String(length=128), nullable=True))
    op.add_column('pelanggan', sa.Column('toko_id', sa.Integer(), nullable=True))
    op.add_column('pelanggan', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'pelanggan', 'toko', ['toko_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pelanggan', type_='foreignkey')
    op.drop_column('pelanggan', 'is_deleted')
    op.drop_column('pelanggan', 'toko_id')
    op.drop_column('pelanggan', 'createdAt')
    op.drop_column('pelanggan', 'email')
    op.drop_column('pelanggan', 'phone')
    op.drop_column('pelanggan', 'name')
    # ### end Alembic commands ###
