"""empty message

Revision ID: 4f31afb81027
Revises: da547661db9b
Create Date: 2022-05-20 10:53:53.744360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f31afb81027'
down_revision = 'da547661db9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pelanggan_id', table_name='pelanggan')
    op.drop_table('pelanggan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pelanggan',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('createdAt', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('toko_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.id'], name='pelanggan_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_pelanggan_id', 'pelanggan', ['id'], unique=False)
    # ### end Alembic commands ###
