"""empty message

Revision ID: 560aebfa9a02
Revises: cb039bf4affd
Create Date: 2022-05-23 08:14:14.557376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560aebfa9a02'
down_revision = 'cb039bf4affd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pajak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('nominal', sa.BigInteger(), nullable=True),
    sa.Column('type_disc', sa.Integer(), nullable=True),
    sa.Column('toko_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pajak_id'), 'pajak', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pajak_id'), table_name='pajak')
    op.drop_table('pajak')
    # ### end Alembic commands ###
