"""empty message

Revision ID: 5a8d1c7945f8
Revises: 1914bd03be84
Create Date: 2022-05-15 16:17:24.553304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8d1c7945f8'
down_revision = '1914bd03be84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toko', sa.Column('address', sa.String(length=384), nullable=True))
    op.add_column('toko', sa.Column('province', sa.String(length=256), nullable=True))
    op.add_column('toko', sa.Column('city', sa.String(length=256), nullable=True))
    op.add_column('toko', sa.Column('district', sa.String(length=256), nullable=True))
    op.add_column('toko', sa.Column('village', sa.String(length=256), nullable=True))
    op.add_column('toko', sa.Column('category', sa.String(length=128), nullable=True))
    op.add_column('toko', sa.Column('photo_logo', sa.Text(), nullable=True))
    op.add_column('toko', sa.Column('photo_logo_url', sa.Text(), nullable=True))
    op.add_column('toko', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toko', 'is_deleted')
    op.drop_column('toko', 'photo_logo_url')
    op.drop_column('toko', 'photo_logo')
    op.drop_column('toko', 'category')
    op.drop_column('toko', 'village')
    op.drop_column('toko', 'district')
    op.drop_column('toko', 'city')
    op.drop_column('toko', 'province')
    op.drop_column('toko', 'address')
    # ### end Alembic commands ###
