"""empty message

Revision ID: 5c93c566b1c9
Revises: 029c236e0b61
Create Date: 2022-05-23 12:39:58.295273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c93c566b1c9'
down_revision = '029c236e0b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('photo_article', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('photo_article_url', sa.Text(), nullable=True))
    op.drop_column('article', 'photo_banner_url')
    op.drop_column('article', 'photo_banner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('photo_banner', mysql.TEXT(), nullable=True))
    op.add_column('article', sa.Column('photo_banner_url', mysql.TEXT(), nullable=True))
    op.drop_column('article', 'photo_article_url')
    op.drop_column('article', 'photo_article')
    # ### end Alembic commands ###
