"""empty message

Revision ID: 618a7eaf9ac8
Revises: 65195c9e4221
Create Date: 2022-05-16 10:47:57.089698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618a7eaf9ac8'
down_revision = '65195c9e4221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
