"""empty message

Revision ID: 65195c9e4221
Revises: ccb76754cf7d
Create Date: 2022-05-16 10:45:42.856996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65195c9e4221'
down_revision = 'ccb76754cf7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
