"""empty message

Revision ID: 676d0889b65b
Revises: 6fc7f3159e73
Create Date: 2022-05-30 13:07:31.741729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676d0889b65b'
down_revision = '6fc7f3159e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
