"""empty message

Revision ID: 67e615b4502c
Revises: 2f67128c8340
Create Date: 2022-05-24 02:49:23.273606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67e615b4502c'
down_revision = '2f67128c8340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactus', sa.Column('label', sa.String(length=256), nullable=True))
    op.add_column('contactus', sa.Column('value', sa.String(length=256), nullable=True))
    op.add_column('contactus', sa.Column('url', sa.String(length=256), nullable=True))
    op.add_column('contactus', sa.Column('photo_contactus', sa.Text(), nullable=True))
    op.add_column('contactus', sa.Column('photo_contactus_url', sa.Text(), nullable=True))
    op.drop_column('contactus', 'paymnet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactus', sa.Column('paymnet', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('contactus', 'photo_contactus_url')
    op.drop_column('contactus', 'photo_contactus')
    op.drop_column('contactus', 'url')
    op.drop_column('contactus', 'value')
    op.drop_column('contactus', 'label')
    # ### end Alembic commands ###
