"""empty message

Revision ID: 6c0f6753e928
Revises: 67e615b4502c
Create Date: 2022-05-25 11:17:38.695712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0f6753e928'
down_revision = '67e615b4502c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_code', sa.String(length=256), nullable=True),
    sa.Column('nama_cart', sa.String(length=256), nullable=True),
    sa.Column('ordered', sa.Boolean(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('total_disc', sa.Float(), nullable=True),
    sa.Column('total_pajak', sa.Float(), nullable=True),
    sa.Column('total_service_fee', sa.Float(), nullable=True),
    sa.Column('grand_total_price', sa.Float(), nullable=True),
    sa.Column('total_item', sa.Integer(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('toko_id', sa.Integer(), nullable=True),
    sa.Column('disc_id', sa.Integer(), nullable=True),
    sa.Column('pajak_id', sa.Integer(), nullable=True),
    sa.Column('ordertype_id', sa.Integer(), nullable=True),
    sa.Column('labelorder_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['disc_id'], ['discount.id'], ),
    sa.ForeignKeyConstraint(['labelorder_id'], ['labelorder.id'], ),
    sa.ForeignKeyConstraint(['ordertype_id'], ['ordertype.id'], ),
    sa.ForeignKeyConstraint(['pajak_id'], ['pajak.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.create_table('cart_servicefee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('servicefee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['servicefee_id'], ['servicefee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_servicefee_id'), 'cart_servicefee', ['id'], unique=False)
    op.create_table('cartitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('ordered', sa.Boolean(), nullable=True),
    sa.Column('ordered_at', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('hpp', sa.Float(), nullable=True),
    sa.Column('total_disc', sa.Float(), nullable=True),
    sa.Column('grand_total_price', sa.Float(), nullable=True),
    sa.Column('is_cancel', sa.Boolean(), nullable=True),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('menu_kat_id', sa.Integer(), nullable=True),
    sa.Column('toko_id', sa.Integer(), nullable=True),
    sa.Column('disc_id', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['disc_id'], ['discount.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['menu_kat_id'], ['kategori_menu.id'], ),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartitem_id'), 'cartitem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartitem_id'), table_name='cartitem')
    op.drop_table('cartitem')
    op.drop_index(op.f('ix_cart_servicefee_id'), table_name='cart_servicefee')
    op.drop_table('cart_servicefee')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###
