"""empty message

Revision ID: 6fc7f3159e73
Revises: 64cf772a15b6
Create Date: 2022-05-30 13:07:02.368571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc7f3159e73'
down_revision = '64cf772a15b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
