"""empty message

Revision ID: 748074869c66
Revises: 071c6483c0a1
Create Date: 2022-05-30 17:22:38.170152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748074869c66'
down_revision = '071c6483c0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historystockmenu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adjustment_stock', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historystockmenu_id'), 'historystockmenu', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historystockmenu_id'), table_name='historystockmenu')
    op.drop_table('historystockmenu')
    # ### end Alembic commands ###
