"""empty message

Revision ID: 7558a2c6ad14
Revises: 787c3603c31a
Create Date: 2022-05-14 20:34:02.681413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7558a2c6ad14'
down_revision = '787c3603c31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('account', sa.Column('account_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'account_type')
    op.drop_column('account', 'address')
    # ### end Alembic commands ###
