"""empty message

Revision ID: 787c3603c31a
Revises: 4636abb17993
Create Date: 2022-05-14 20:11:31.873857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787c3603c31a'
down_revision = '4636abb17993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('createdAt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'createdAt')
    # ### end Alembic commands ###
