"""empty message

Revision ID: 7df3017ea9a6
Revises: 3559eb4b66af
Create Date: 2022-05-14 22:05:26.387055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df3017ea9a6'
down_revision = '3559eb4b66af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
