"""empty message

Revision ID: 80b353fbd406
Revises: ba711944394e
Create Date: 2022-05-16 06:03:35.436579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b353fbd406'
down_revision = 'ba711944394e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
