"""empty message

Revision ID: 86a3cbf5d422
Revises: 340763221357
Create Date: 2022-05-14 12:26:05.250694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a3cbf5d422'
down_revision = '340763221357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
