"""empty message

Revision ID: 89f112d8c0cc
Revises: 80b353fbd406
Create Date: 2022-05-16 06:07:02.716547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f112d8c0cc'
down_revision = '80b353fbd406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
