"""empty message

Revision ID: 8d5761233273
Revises: ae585b9c136d
Create Date: 2022-05-23 09:38:15.697880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d5761233273'
down_revision = 'ae585b9c136d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank', sa.Column('created_at', sa.String(length=128), nullable=True))
    op.drop_column('bank', 'createdAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank', sa.Column('createdAt', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('bank', 'created_at')
    # ### end Alembic commands ###
