"""empty message

Revision ID: 8f303626d3b0
Revises: be4282f23ede
Create Date: 2022-05-23 07:04:32.612822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f303626d3b0'
down_revision = 'be4282f23ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('nominal', sa.BigInteger(), nullable=True),
    sa.Column('toko_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_table('discount')
    # ### end Alembic commands ###
