"""empty message

Revision ID: 8f33d0272a72
Revises: 1316c40a99ef
Create Date: 2022-05-16 16:57:00.259015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f33d0272a72'
down_revision = '1316c40a99ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kategori_menu', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('kategori_menu', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('kategori_menu', sa.Column('createdAt', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kategori_menu', 'createdAt')
    op.drop_column('kategori_menu', 'is_deleted')
    op.drop_column('kategori_menu', 'name')
    # ### end Alembic commands ###
