"""empty message

Revision ID: 93192f2ba992
Revises: 6c0f6753e928
Create Date: 2022-05-25 15:08:36.836595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93192f2ba992'
down_revision = '6c0f6753e928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_price_item', sa.Float(), nullable=True))
    op.drop_column('cart', 'total_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_price', mysql.FLOAT(), nullable=True))
    op.drop_column('cart', 'total_price_item')
    # ### end Alembic commands ###
