"""empty message

Revision ID: 979c6f618e00
Revises: 0bae35c85597
Create Date: 2022-05-23 08:55:03.677880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '979c6f618e00'
down_revision = '0bae35c85597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicefee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('nominal', sa.BigInteger(), nullable=True),
    sa.Column('toko_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicefee_id'), 'servicefee', ['id'], unique=False)
    op.drop_index('ix_service_fee_id', table_name='service_fee')
    op.drop_table('service_fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_fee',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('nominal', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('toko_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createdAt', mysql.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.id'], name='service_fee_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_service_fee_id', 'service_fee', ['id'], unique=False)
    op.drop_index(op.f('ix_servicefee_id'), table_name='servicefee')
    op.drop_table('servicefee')
    # ### end Alembic commands ###
