"""empty message

Revision ID: b0fab7af7728
Revises: e6a24c94f4d9
Create Date: 2022-05-14 12:22:48.993835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fab7af7728'
down_revision = 'e6a24c94f4d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'phone')
    # ### end Alembic commands ###
