"""empty message

Revision ID: b5b013aa1291
Revises: ee3c3e389c12
Create Date: 2022-05-16 18:13:31.107207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b013aa1291'
down_revision = 'ee3c3e389c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
