"""empty message

Revision ID: ba711944394e
Revises: 11da3c9ca98c
Create Date: 2022-05-16 06:02:20.409638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba711944394e'
down_revision = '11da3c9ca98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
