"""empty message

Revision ID: bae85593666b
Revises: c09eb8377d99
Create Date: 2022-05-21 20:20:47.881506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bae85593666b'
down_revision = 'c09eb8377d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordertype', sa.Column('desc', sa.String(length=256), nullable=True))
    op.drop_column('ordertype', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordertype', sa.Column('note', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('ordertype', 'desc')
    # ### end Alembic commands ###
