"""empty message

Revision ID: bb34cd6ba903
Revises: 89f112d8c0cc
Create Date: 2022-05-16 06:07:49.602787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb34cd6ba903'
down_revision = '89f112d8c0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'createdAt')
    op.drop_column('toko', 'createdAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toko', sa.Column('createdAt', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('createdAt', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
