"""empty message

Revision ID: bd5fd7fd7b26
Revises: 534711f489f1
Create Date: 2022-05-16 18:18:40.191852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5fd7fd7b26'
down_revision = '534711f489f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
