"""empty message

Revision ID: c09eb8377d99
Revises: 9d79ef518a73
Create Date: 2022-05-21 19:12:26.973731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c09eb8377d99'
down_revision = '9d79ef518a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('note', sa.String(length=256), nullable=True))
    op.add_column('table', sa.Column('is_booked', sa.Boolean(), nullable=True))
    op.drop_constraint('table_ibfk_1', 'table', type_='foreignkey')
    op.drop_column('table', 'desc')
    op.drop_column('table', 'kategori_id')
    op.drop_column('table', 'photo_menu')
    op.drop_column('table', 'harga_asli')
    op.drop_column('table', 'photo_menu_url')
    op.drop_column('table', 'harga_jual')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('harga_jual', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('table', sa.Column('photo_menu_url', mysql.TEXT(), nullable=True))
    op.add_column('table', sa.Column('harga_asli', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('table', sa.Column('photo_menu', mysql.TEXT(), nullable=True))
    op.add_column('table', sa.Column('kategori_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('table', sa.Column('desc', mysql.VARCHAR(length=384), nullable=True))
    op.create_foreign_key('table_ibfk_1', 'table', 'kategori_menu', ['kategori_id'], ['id'])
    op.drop_column('table', 'is_booked')
    op.drop_column('table', 'note')
    # ### end Alembic commands ###
