"""empty message

Revision ID: c7f7d6bb5eea
Revises: 0708d8870fc6
Create Date: 2022-05-30 13:08:37.364556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f7d6bb5eea'
down_revision = '0708d8870fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('callbackxendit', sa.Column('createdAt', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('callbackxendit', 'createdAt')
    # ### end Alembic commands ###
