"""empty message

Revision ID: cb039bf4affd
Revises: 8f303626d3b0
Create Date: 2022-05-23 07:09:33.160820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb039bf4affd'
down_revision = '8f303626d3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount', sa.Column('type_disc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discount', 'type_disc')
    # ### end Alembic commands ###
