"""empty message

Revision ID: ccb76754cf7d
Revises: a2cf7f0344cc
Create Date: 2022-05-16 10:30:43.671512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb76754cf7d'
down_revision = 'a2cf7f0344cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
