"""empty message

Revision ID: cf4708c14066
Revises: 8f33d0272a72
Create Date: 2022-05-16 18:09:43.984439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4708c14066'
down_revision = '8f33d0272a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
