"""empty message

Revision ID: d88f159db8b8
Revises: bb34cd6ba903
Create Date: 2022-05-16 06:08:12.198703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88f159db8b8'
down_revision = 'bb34cd6ba903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('createdAt', sa.String(length=128), nullable=True))
    op.add_column('toko', sa.Column('createdAt', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toko', 'createdAt')
    op.drop_column('account', 'createdAt')
    # ### end Alembic commands ###
