"""empty message

Revision ID: da547661db9b
Revises: 6eb92dd64bbc
Create Date: 2022-05-20 10:51:34.236401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da547661db9b'
down_revision = '6eb92dd64bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
