"""empty message

Revision ID: dfca59b210f6
Revises: 2c1c1b63bd8d
Create Date: 2022-05-17 02:29:47.633759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfca59b210f6'
down_revision = '2c1c1b63bd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['phone'])
    op.create_unique_constraint(None, 'account', ['name'])
    op.create_unique_constraint(None, 'account', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
