"""empty message

Revision ID: e2f1a909f28e
Revises: 2eef46a2ffd9
Create Date: 2022-05-14 23:25:36.986957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f1a909f28e'
down_revision = '2eef46a2ffd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
