"""empty message

Revision ID: ee3c3e389c12
Revises: cf4708c14066
Create Date: 2022-05-16 18:09:55.604181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3c3e389c12'
down_revision = 'cf4708c14066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
