"""empty message

Revision ID: fbfccd497eb7
Revises: bd5fd7fd7b26
Create Date: 2022-05-16 18:22:13.887416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfccd497eb7'
down_revision = 'bd5fd7fd7b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
