"""empty message

Revision ID: fe160b0d6353
Revises: dfca59b210f6
Create Date: 2022-05-17 02:31:44.417176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe160b0d6353'
down_revision = 'dfca59b210f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='account')
    op.drop_index('name', table_name='account')
    op.drop_index('phone', table_name='account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone', 'account', ['phone'], unique=False)
    op.create_index('name', 'account', ['name'], unique=False)
    op.create_index('email', 'account', ['email'], unique=False)
    # ### end Alembic commands ###
